### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by kxiserino** [JuiceFN/JuiceFN-Aes-Generator#1]
how to i install ?

**Comment by jwhazy** [comment]
> how to i install ?

Double click

**Comment by jwhazy** [comment]
Double click

**Comment by AlexDev404** [comment]
LMAO

**Comment by AlexDev404** [comment]
@KaiserBloo Dude just compile it or something idk.
Or just make one yourself by using the endpoint https://benbot.app/api/v1/aes
